//
// NotificationFilter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NotificationFilter: Codable, JSONEncodable, Hashable {

    static let offsetRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    static let limitRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    static let skipRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var offset: Int?
    public var limit: Int?
    public var skip: Int?
    public var order: LikeFilterOrder?
    public var fields: NotificationFields?

    public init(offset: Int? = nil, limit: Int? = nil, skip: Int? = nil, order: LikeFilterOrder? = nil, fields: NotificationFields? = nil) {
        self.offset = offset
        self.limit = limit
        self.skip = skip
        self.order = order
        self.fields = fields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case offset
        case limit
        case skip
        case order
        case fields
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(offset, forKey: .offset)
        try container.encodeIfPresent(limit, forKey: .limit)
        try container.encodeIfPresent(skip, forKey: .skip)
        try container.encodeIfPresent(order, forKey: .order)
        try container.encodeIfPresent(fields, forKey: .fields)
    }
}

