//
// PostFieldsOneOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PostFieldsOneOf: Codable, JSONEncodable, Hashable {

    public var id: Bool?
    public var petName: Bool?
    public var petType: Bool?
    public var petBreed: Bool?
    public var gender: Bool?
    public var photo: Bool?
    public var description: Bool?
    public var preferredHome: Bool?
    public var status: Bool?
    public var createdAt: Bool?
    public var userId: Bool?

    public init(id: Bool? = nil, petName: Bool? = nil, petType: Bool? = nil, petBreed: Bool? = nil, gender: Bool? = nil, photo: Bool? = nil, description: Bool? = nil, preferredHome: Bool? = nil, status: Bool? = nil, createdAt: Bool? = nil, userId: Bool? = nil) {
        self.id = id
        self.petName = petName
        self.petType = petType
        self.petBreed = petBreed
        self.gender = gender
        self.photo = photo
        self.description = description
        self.preferredHome = preferredHome
        self.status = status
        self.createdAt = createdAt
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case petName
        case petType
        case petBreed
        case gender
        case photo
        case description
        case preferredHome
        case status
        case createdAt
        case userId
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(petName, forKey: .petName)
        try container.encodeIfPresent(petType, forKey: .petType)
        try container.encodeIfPresent(petBreed, forKey: .petBreed)
        try container.encodeIfPresent(gender, forKey: .gender)
        try container.encodeIfPresent(photo, forKey: .photo)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(preferredHome, forKey: .preferredHome)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(userId, forKey: .userId)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        id = try container.decodeIfPresent(Bool.self, forKey: .id)
        petName = try container.decodeIfPresent(Bool.self, forKey: .petName)
        petType = try container.decodeIfPresent(Bool.self, forKey: .petType)
        petBreed = try container.decodeIfPresent(Bool.self, forKey: .petBreed)
        gender = try container.decodeIfPresent(Bool.self, forKey: .gender)
        photo = try container.decodeIfPresent(Bool.self, forKey: .photo)
        description = try container.decodeIfPresent(Bool.self, forKey: .description)
        preferredHome = try container.decodeIfPresent(Bool.self, forKey: .preferredHome)
        status = try container.decodeIfPresent(Bool.self, forKey: .status)
        createdAt = try container.decodeIfPresent(Bool.self, forKey: .createdAt)
        userId = try container.decodeIfPresent(Bool.self, forKey: .userId)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("id")
        nonAdditionalPropertyKeys.insert("petName")
        nonAdditionalPropertyKeys.insert("petType")
        nonAdditionalPropertyKeys.insert("petBreed")
        nonAdditionalPropertyKeys.insert("gender")
        nonAdditionalPropertyKeys.insert("photo")
        nonAdditionalPropertyKeys.insert("description")
        nonAdditionalPropertyKeys.insert("preferredHome")
        nonAdditionalPropertyKeys.insert("status")
        nonAdditionalPropertyKeys.insert("createdAt")
        nonAdditionalPropertyKeys.insert("userId")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

