//
// MessageFieldsOneOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MessageFieldsOneOf: Codable, JSONEncodable, Hashable {

    public var id: Bool?
    public var senderId: Bool?
    public var recipientId: Bool?
    public var postId: Bool?
    public var content: Bool?
    public var createdAt: Bool?

    public init(id: Bool? = nil, senderId: Bool? = nil, recipientId: Bool? = nil, postId: Bool? = nil, content: Bool? = nil, createdAt: Bool? = nil) {
        self.id = id
        self.senderId = senderId
        self.recipientId = recipientId
        self.postId = postId
        self.content = content
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case senderId
        case recipientId
        case postId
        case content
        case createdAt
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(senderId, forKey: .senderId)
        try container.encodeIfPresent(recipientId, forKey: .recipientId)
        try container.encodeIfPresent(postId, forKey: .postId)
        try container.encodeIfPresent(content, forKey: .content)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        id = try container.decodeIfPresent(Bool.self, forKey: .id)
        senderId = try container.decodeIfPresent(Bool.self, forKey: .senderId)
        recipientId = try container.decodeIfPresent(Bool.self, forKey: .recipientId)
        postId = try container.decodeIfPresent(Bool.self, forKey: .postId)
        content = try container.decodeIfPresent(Bool.self, forKey: .content)
        createdAt = try container.decodeIfPresent(Bool.self, forKey: .createdAt)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("id")
        nonAdditionalPropertyKeys.insert("senderId")
        nonAdditionalPropertyKeys.insert("recipientId")
        nonAdditionalPropertyKeys.insert("postId")
        nonAdditionalPropertyKeys.insert("content")
        nonAdditionalPropertyKeys.insert("createdAt")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

