//
// PingResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PingResponse: Codable, JSONEncodable, Hashable {

    public var greeting: String?
    public var date: String?
    public var url: String?
    public var headers: PingResponseHeaders?

    public init(greeting: String? = nil, date: String? = nil, url: String? = nil, headers: PingResponseHeaders? = nil) {
        self.greeting = greeting
        self.date = date
        self.url = url
        self.headers = headers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case greeting
        case date
        case url
        case headers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(greeting, forKey: .greeting)
        try container.encodeIfPresent(date, forKey: .date)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(headers, forKey: .headers)
    }
}

