//
// PostIncludeFilterItems.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PostIncludeFilterItems: Codable, JSONEncodable, Hashable {

    public enum Relation: String, Codable, CaseIterable {
        case user = "user"
    }
    public var relation: Relation?
    public var scope: PostScopeFilter?

    public init(relation: Relation? = nil, scope: PostScopeFilter? = nil) {
        self.relation = relation
        self.scope = scope
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case relation
        case scope
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(relation, forKey: .relation)
        try container.encodeIfPresent(scope, forKey: .scope)
    }
}

