//
// MessageFields.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum MessageFields: Codable, JSONEncodable, Hashable {
    case typeMessageFieldsOneOf(MessageFieldsOneOf)
    case typeSetString(Set<String>)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeMessageFieldsOneOf(let value):
            try container.encode(value)
        case .typeSetString(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(MessageFieldsOneOf.self) {
            self = .typeMessageFieldsOneOf(value)
        } else if let value = try? container.decode(Set<String>.self) {
            self = .typeSetString(value)
        } else {
            throw DecodingError.typeMismatch(Self.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of MessageFields"))
        }
    }
}
