//
// PostScopeFilterFields.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum PostScopeFilterFields: Codable, JSONEncodable, Hashable {
    case typeSetString(Set<String>)
    case typeDictionary([String: AnyCodable])

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeSetString(let value):
            try container.encode(value)
        case .typeDictionary(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(Set<String>.self) {
            self = .typeSetString(value)
        } else if let value = try? container.decode([String: AnyCodable].self) {
            self = .typeDictionary(value)
        } else {
            throw DecodingError.typeMismatch(Self.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of PostScopeFilterFields"))
        }
    }
}
