//
// PostFields.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum PostFields: Codable, JSONEncodable, Hashable {
    case typePostFieldsOneOf(PostFieldsOneOf)
    case typeSetString(Set<String>)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typePostFieldsOneOf(let value):
            try container.encode(value)
        case .typeSetString(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(PostFieldsOneOf.self) {
            self = .typePostFieldsOneOf(value)
        } else if let value = try? container.decode(Set<String>.self) {
            self = .typeSetString(value)
        } else {
            throw DecodingError.typeMismatch(Self.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of PostFields"))
        }
    }
}
